In [6]:
import numpy as np
from xarray import DataArray
import torch
from torch.utils.data import DataLoader

In [15]:
class DataArrayDataset:
    def __init__(self, arr):
        self.arr = arr

    def __getitem__(self, i):
        return self.arr[i].to_numpy()

    def __len__(self):
        return self.arr.shape[0]

In [3]:
a = DataArray(np.arange(10))
a

<xarray.DataArray (dim_0: 10)>
array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
Dimensions without coordinates: dim_0

In [14]:
ds = DataArrayDataset(a)

In [19]:
dl = DataLoader(ds, batch_size=1, num_workers=2)

In [20]:
for x in dl:
    print(x)

tensor([0])
tensor([1])
tensor([2])
tensor([3])
tensor([4])
tensor([5])
tensor([6])
tensor([7])
tensor([8])
tensor([9])


---

In [ ]:
%pip install pystac_client==0.7.5 stackstac==0.5.0 humanize==4.8.0

In [25]:
import pystac_client
from shapely.geometry import mapping

from rastervision.pipeline.file_system.utils import json_to_file
from rastervision.core.box import Box
from rastervision.core.data import XarraySourceConfig, STACItemConfig, Scene
from rastervision.pytorch_learner.dataset import SemanticSegmentationSlidingWindowGeoDataset

In [2]:
bbox = Box(ymin=48.8155755, xmin=2.224122, ymax=48.902156, xmax=2.4697602)

In [3]:
raster_source_config = XarraySourceConfig(
    stac=STACItemConfig(
        uri='xarray_source_config/item.json', 
        assets=[
        'coastal', # B01
        'blue', # B02
        'green', # B03
        # 'red', # B04
        # 'rededge1', # B05
        # 'rededge2', # B06
        # 'rededge3', # B07
        # 'nir', # B08
        # 'nir08', # B8A
        # 'nir09', # B09
        # 'swir16', # B11
        # 'swir22', # B12
    ]),
    bbox_map_coords=tuple(bbox),
)

In [23]:
rs = raster_source_config.build()
scene = Scene(id='', raster_source=rs)

In [27]:
ds = SemanticSegmentationSlidingWindowGeoDataset(
    scene=scene,
    size=100,
    stride=100,
)

This fails:

In [33]:
dl = DataLoader(ds, batch_size=1, num_workers=2)
len(dl)

162

In [ ]:
for _, (x, _) in zip(range(4), dl):
    print(x.shape)

---

In [ ]:
import multiprocessing

# Define a function that each process will execute
def worker_function(process_num):
    print(f"Worker {process_num} is doing some work")

if __name__ == "__main__":
    # Create a list of processes
    processes = []

    # Define the number of processes you want to create
    num_processes = 4

    # Start and run the processes
    for i in range(num_processes):
        process = multiprocessing.Process(target=worker_function, args=(i,))
        processes.append(process)
        process.start()

    # Wait for all processes to complete
    for process in processes:
        process.join()

    print("All processes have completed")
